# A list of biomes to prevent teleportation to.
biome-blacklist:
  - OCEAN
  - RIVER
  - DEEP_OCEAN

# A list of unsafe blocks
block-blacklist:
  - LAVA
  - STATIONARY_LAVA
  - FIRE
  - WATER
  - STATIONARY_WATER

# world - the world to teleport to
# max-x - The max X coordinate for teleport locations.
# max-y - The max Y coordinate for teleport locations.
# cooldown - The delay, in seconds, required between teleports. Set to '0' to disable.
world: world
max-x: 5000
max-z: 5000
cooldown: 0
