name: DHRandomTP
main: net.digitalhazards.rtp.RandomTeleport
version: 0.0.2
description: Teleports you to a random place in the wild.
author: Timothy Copeland

commands:
  randomtp:
    usage: /<command>
    description: Teleports you to a random location.
    aliases: [rtp]
